//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HouseSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HouseSet()
        {
            this.ImageSet = new HashSet<ImageSet>();
            this.TransactionSet = new HashSet<TransactionSet>();
        }
    
        
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter an address")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Please enter a price")]
        public decimal Price { get; set; }

        [Required(ErrorMessage = "Please enter a latitude")]
        public decimal Latitude { get; set; }

        [Required(ErrorMessage = "Please enter a longitude")]
        public decimal Longitude { get; set; }

        [Required(ErrorMessage = "Please enter a number")]
        public string Bedroom { get; set; }

        [Required(ErrorMessage = "Please enter a number")]
        public string Bathroom { get; set; }

        [Required(ErrorMessage = "Please enter a number")]
        public string Parking { get; set; }

        [Required(ErrorMessage = "Please enter a area number")]
        public decimal Area { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageSet> ImageSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionSet> TransactionSet { get; set; }
    }
}
