//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageSet
    {
        public int Id { get; set; }
        public string Path { get; set; }
        public string Name { get; set; }
        public int HouseId { get; set; }
    
        public virtual HouseSet HouseSet { get; set; }
    }
}
