//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateSet
    {
        public int Id { get; set; }
        public Nullable<short> AgentMark { get; set; }
        public Nullable<short> HouseMark { get; set; }
        public Nullable<short> WebSiteMark { get; set; }
        public Nullable<short> OverallMark { get; set; }
    }
}
