//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TransactionSet
    {
        public int Id { get; set; }
        public System.DateTime Time { get; set; }

        [Required(ErrorMessage = "Please enter a accept price")]
        public decimal Price { get; set; }

        [Required(ErrorMessage = "Please enter a type i.e order, buy or bidding")]
        public string Type { get; set; }
        public string AspNetUsersId { get; set; }
        public int House_Id { get; set; }
        public int Agent_Id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual HouseSet HouseSet { get; set; }
        public virtual AgentSet AgentSet { get; set; }
    }
}
